language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch

# command to install dependencies
install:
  - pip install -r requirements.txt -t lib
  - pip install coveralls

# command to run tests
script:
  - python test.py

after_success:
  - coverage run --source=./services,./handler.py test.py
  - coveralls